spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://ec-db-mysql:3306/ec_uac?characterEncoding=utf8&useSSL=false

mybatis:
  type-aliases-package: com.ec.provider.uac.model.domain
  mapper-locations: classpath:mapper/*.xml,classpath*:sdk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.ec.common.core.mybatis.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

liquibase:
  change-log: classpath:liquibase/index.xml
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

security:
  oauth2:
    client:
      clientId: ec-client-uac
      clientSecret: ecClientSecret
      access-token-uri: http://ec-gateway:7979/uac/oauth/token
      user-authorization-uri: http://ec-gateway:7979/uac/oauth/authorize
    resource:
      id: ec-resource-uac
      filter-order: 3

ec:
  enableSqlLogInterceptor: false
  aliyun:
    rocketMq:
      enable: true
      reliableMessageConsumer: false
      reliableMessageProducer: true
      instanceName: ec-provider-uac
      consumerGroup: CID_UAC
      producerGroup: PID_UAC
  auth:
    rest-pwd-url: http://dev-login.ec.net/resetPwd?resetPwdKey=
    active-user-url: http://dev-api.ec.net:7979/uac/auth/activeUser/
    refresh-token-url: http://dev-api.ec.net:7979/uac/oauth/token
  token:
    interceptor:
      enable: true
  oauth2:
    jwtSigningKey: ec
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
  security:
    social:
      filterProcessesUrl: /auth/callback
      qq:
        app-id: 101431061
        app-secret: 0154c848f45fc705412462d4f99a592c
        providerId: qq
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        providerId: weixin
    code:
      image:
        expireIn: 180
        url: /auth/register,/auth/submitResetPwdEmail,/auth/code/sms
      sms:
        expireIn: 600
        url: /uac/auth/submitResetPwdPhone
        mobileMaxSendCount: 1
        ipMaxSendCount: 2
        totalMaxSendCount: 3
    oauth2:
      tokenStore: jwt
      clients[0]:
        clientId: ec-client-uac
        clientSecret: ecClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[1]:
        clientId: ec-browser
        clientSecret: ecClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[2]:
        clientId: ec-client-gateway
        clientSecret: ecClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[3]:
        clientId: ec-client-zipkin
        clientSecret: ecClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[4]:
        clientId: ec-client-mdc
        clientSecret: ecClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[5]:
        clientId: ec-client-omc
        clientSecret: ecClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[6]:
        clientId: ec-client-opc
        clientSecret: ecClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"
      clients[7]:
        clientId: ec-client-tpc
        clientSecret: ecClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"